tasks:
  - name: Setup PlatformIO
    before: |
      pip3 install -U platformio
      platformio upgrade --dev
      platformio update
    init: platformio run --list-targets

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces

