tasks:
  - name: Setup PlatformIO
    before: |
      pip3 install -U platformio
      platformio upgrade --dev
      platformio update
    init: platformio run --list-targets

#  - name: Build Firmware
#    init: platformio run

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - CoenraadS.bracket-pair-colorizer
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces

